version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    working_directory: ./bin
    steps:
      - checkout
      - run: yarn install
      - run:
          name: scaffold-init
          command: node struct-init scaffold-react test
      - run:
          name: add template
          command: node struct add
      - run:
          name: delete template
          command: node struct delete
      - run:
          name: list template
          command: node struct list
