version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-scaffold-init-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-scaffold-init-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
            - ~/.cache/yarn
          key: v1-scaffold-init-{{ checksum "yarn.lock" }}
      - run: yarn test
