version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run: yarn install
      - run:
          name: scaffold-init
          command: cd bin && node struct-init scaffold-react test
      - run:
          name: add template
          command: cd bin && node struct add
      - run:
          name: delete template
          command: cd bin && node struct delete
      - run:
          name: list template
          command: cd bin && node struct list
